version: '3.1'

networks: 
    tech_challenge_hackathon_net:
      driver: bridge

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - tech_challenge_hackathon_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root!
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root!
      ME_CONFIG_MONGODB_URL: mongodb://root:root!@mongo:27017/

  rabbit:
    image: masstransit/rabbitmq
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - tech_challenge_hackathon_net
      
  web:
    image: techchallenge-hackathon-api:v1
    depends_on:
      - mongo
      - rabbit
    networks:
      - tech_challenge_hackathon_net
    ports:
      - "8080:8080"